name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php-lint:
    runs-on: ubuntu-latest
    name: Linting PHP
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install
      - name: Linting
        run: ./vendor/bin/php-cs-fixer fix --dry-run --verbose --ansi --config .php-cs-fixer.php

  php-tests:
    runs-on: ubuntu-20.04
    name: Testing PHP
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: db
          MYSQL_USER: db
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify MySQL
        run: |
          mysql --version
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -udb -psecret -e "SHOW DATABASES"
      - name: Build
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
      - name: Execute Tests
        env:
          APP_ENV: testing
          MYSQL_DATABASE:
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_USERNAME: db
          DB_PASSWORD: secret
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          CACHE_DRIVER: array
          DB_DATABASE:
          MAIL_MAILER: array
          QUEUE_CONNECTION: sync
          SESSION_DRIVER: array
        run: vendor/bin/phpunit --testdox
