name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php-lint:
    runs-on: ubuntu-latest
    name: Linting PHP
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install
      - name: Linting
        run: ./vendor/bin/php-cs-fixer fix --dry-run --verbose --ansi --config .php-cs-fixer.php

  php-tests:
    runs-on: ubuntu-20.04
    name: Testing PHP
    services:
      postgres:
        image: postgres:16.1-alpine3.19
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432
        options: --health-cmd="pg_isready -U postgres -d postgres" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify Postgres
        run: |
          psql --version
          PGPASSWORD=password psql --host 127.0.0.1 --port ${{ job.services.postgres.ports['5432'] }} -U postgres -d postgres -c "\l"
      - name: Build
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
      - name: Execute Tests
        env:
          APP_ENV: testing
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_DATABASE: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: password
          CACHE_DRIVER: array
          MAIL_MAILER: array
          QUEUE_CONNECTION: sync
          SESSION_DRIVER: array
        run: php artisan test
